# Konfigurasi TCP untuk Perangkat Tepi (Edge Device)
listener 1883
protocol mqtt
allow_anonymous true

# Konfigurasi WebSockets untuk Antarmuka Dasbor Next.js
listener 9001
protocol websockets
allow_anonymous true