# Konfigurasi Pialang MQTT Eclipse Mosquitto - Ocusense AI

# Mengizinkan koneksi masuk tanpa kata sandi (Hanya untuk fase pengembangan lokal/purwarupa)
allow_anonymous true

# Protokol TCP Murni (Port 1883) -> Digunakan oleh Edge Device (Raspberry Pi / Python) & Backend Next.js
listener 1883 0.0.0.0
protocol mqtt

# Protokol WebSockets (Port 9001) -> Digunakan oleh Frontend Next.js / Klien Browser
listener 9001 0.0.0.0
protocol websockets